// import {sessionParametersWater} from './data/parametersForTests';
import extras from '../../calculations/extras';

describe('tests for reportGenerationService file', () => {
  test('filterTbTsSamples function', () => {
    let samples: Sample[] = [
      {
        dateSampled: '13/03/2019',
        depth: {from: 0, to: 0.1},
        dpSampleId: 'BH101',
        labName: 'Unknown',
        labSampleId: '213536-1',
        labReportNo: null,
        matrixType: 'soil',
        measurements: [],
        sampleType: 'Normal',
        isTripBlank: true,
        isTripSpike: false,
        isRinsate: false,
        soilType: 'Sand',
      },
      {
        dateSampled: '13/03/2019',
        depth: {from: 0, to: 0.1},
        dpSampleId: 'BH102',
        labName: 'Unknown',
        labSampleId: '213536-2',
        labReportNo: null,
        matrixType: 'soil',
        measurements: [],
        sampleType: 'Normal',
        isTripBlank: false,
        isTripSpike: true,
        isRinsate: false,
        soilType: 'Sand',
      },
      ,
      {
        dateSampled: '13/03/2019',
        depth: {from: 0, to: 0.1},
        dpSampleId: 'BH103',
        labName: 'Unknown',
        labSampleId: '213536-2',
        labReportNo: null,
        matrixType: 'soil',
        measurements: [],
        sampleType: 'Normal',
        isTripBlank: false,
        isTripSpike: false,
        isRinsate: true,
        soilType: 'Sand',
      },
      {
        dateSampled: '13/03/2019',
        depth: {from: 0, to: 0.1},
        dpSampleId: 'BH104',
        labName: 'Unknown',
        labSampleId: '213536-3',
        labReportNo: null,
        matrixType: 'soil',
        measurements: [],
        sampleType: 'Normal',
        isTripBlank: false,
        isTripSpike: false,
        isRinsate: false,
        soilType: 'Sand',
      },
    ];
    let result: any = {
      samplesWithoutTbTsRinsate: [
        {
          dateSampled: '13/03/2019',
          depth: {from: 0, to: 0.1},
          dpSampleId: 'BH104',
          labName: 'Unknown',
          labSampleId: '213536-3',
          labReportNo: null,
          matrixType: 'soil',
          measurements: [],
          sampleType: 'Normal',
          isTripBlank: false,
          isTripSpike: false,
          isRinsate: false,
          soilType: 'Sand',
        },
      ],
      tbSamples: [
        {
          dateSampled: '13/03/2019',
          depth: {from: 0, to: 0.1},
          dpSampleId: 'BH101',
          labName: 'Unknown',
          labSampleId: '213536-1',
          labReportNo: null,
          matrixType: 'soil',
          measurements: [],
          sampleType: 'Normal',
          isTripBlank: true,
          isTripSpike: false,
          isRinsate: false,
          soilType: 'Sand',
        },
      ],
      tsSamples: [
        {
          dateSampled: '13/03/2019',
          depth: {from: 0, to: 0.1},
          dpSampleId: 'BH102',
          labName: 'Unknown',
          labSampleId: '213536-2',
          labReportNo: null,
          matrixType: 'soil',
          measurements: [],
          sampleType: 'Normal',
          isTripBlank: false,
          isTripSpike: true,
          isRinsate: false,
          soilType: 'Sand',
        },
      ],
      rinsateSamples: [
        {
          dateSampled: '13/03/2019',
          depth: {from: 0, to: 0.1},
          dpSampleId: 'BH103',
          labName: 'Unknown',
          labSampleId: '213536-2',
          labReportNo: null,
          matrixType: 'soil',
          measurements: [],
          sampleType: 'Normal',
          isTripBlank: false,
          isTripSpike: false,
          isRinsate: true,
          soilType: 'Sand',
        },
      ],
    };

    expect(extras.filterTbTsRinsateSamples(samples)).toEqual(result);
  });
});
