process.env.SUPABASE_URL = 'https://homnplhtmvdfxcqcjelr.supabase.co';
process.env.SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvbW5wbGh0bXZkZnhjcWNqZWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTkyMDksImV4cCI6MjA1OTY3NTIwOX0.9G-DX3-KGB_ETJhSvivL7EKLJb9it0RG0AUY3ZL6IEs';
