export const LOAD_APP_STATE = 'LOAD_STATE';

//common
export const ASYNC_ACTION_START = 'ASYNC_ACTION_START';
export const ASYNC_ACTION_END = 'ASYNC_ACTION_END';

export const CONFIRM_ACTION = 'CONFIRM_ACTION';
export const CONFIRM_ACTION_CANCEL = 'CONFIRM_ACTION_CANCEL';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

//sample
export const LOAD_SAMPLES = 'LOAD_SAMPLES';
export const RESET_SAMPLES = 'RESET_SAMPLES';
export const UPDATE_SELECTION_REPORT = 'UPDATE_SELECTION_REPORT';
export const UPDATE_SELECTION_EDIT = 'UPDATE_SELECTION_EDIT';
export const UPDATE_SOIL_TYPE = 'UPDATE_SOIL_TYPE';
export const UPDATE_SAMPLE_DEPTH = 'UPDATE_SAMPLE_DEPTH';
export const UPDATE_PARAMETERS = 'UPDATE_PARAMETERS';
export const UPDATE_TRIP_BLANK = 'UPDATE_TRIP_BLANK';
export const UPDATE_TRIP_SPIKE = 'UPDATE_TRIP_SPIKE';
export const UPDATE_RINSATE = 'UPDATE_RINSATE';
export const SAVE_SAMPLE_DUPLICATE = 'SAVE_SAMPLE_DUPLICATE';
export const SAVE_SAMPLE_ORDER = 'SAVE_SAMPLE_ORDER';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';

//session
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const UPDATE_CHEMICAL_GROUPS = 'UPDATE_CHEMICAL_GROUPS';
export const RESET_SESSION = 'RESET_SESSION';
export const ADD_SESSION_FILE = 'ADD_SESSION_FILE';
export const REMOVE_SESSION_FILE = 'REMOVE_SESSION_FILE';
export const APPLY_BIODEGRADATION = 'APPLY_BIODEGRADATION';
export const SAVE_CHEMICAL_GROUPS = 'SAVE_CHEMICAL_GROUPS';
export const SET_COMBINED_CHEMICALS_DISPLAY = 'SET_COMBINED_CHEMICALS_DISPLAY';
export const HIGHTLIGHT_ALL_DETECTIONS = 'HIGHTLIGHT_ALL_DETECTIONS';
export const TOGGLE_DEPTH_COLUMN = 'TOGGLE_DEPTH_COLUMN';
export const SAVE_CRITERIA = 'SAVE_CRITERIA';
export const SAVE_CURRENT_CRITERIA = 'SAVE_CURRENT_CRITERIA';
export const UPDATE_WASTE_STATISTICS = 'UPDATE_WASTE_STATISTICS';
export const UPDATE_OUTPUT_FORMAT = 'UPDATE_OUTPUT_FORMAT';
export const UPDATE_WATER_ASSESSMENT_PARAMETERS = 'UPDATE_WATER_ASSESSMENT_PARAMETERS';
export const SHOULD_OUTPUT_TCLP = 'SHOULD_OUTPUT_TCLP';
export const SHOULD_OUTPUT_ASLP = 'SHOULD_OUTPUT_ASLP';

//chemical
export const LOAD_CHEMICALS = 'LOAD_CHEMICALS';
export const LOAD_COMBINED_CHEMICALS_DISPLAY_OPTIONS = 'LOAD_COMBINED_CHEMICALS_DISPLAY_OPTIONS';

//report
export const UPDATE_REPORT_PREVIEW = 'UPDATE_REPORT_PREVIEW';
export const EXPORT_REPORT_TO_EXCEL = 'EXPORT_REPORT_TO_EXCEL';
export const UPDATE_REPORT_EDITS = 'UPDATE_REPORT_EDITS';
