const enum ReportColors {
  Red = 'Red',
  Grey = 'Grey',
  Pink = 'Pink',
  Green = 'Green',
  Yellow = 'Yellow',
  Orange = 'Orange',
  DarkGreen = 'DarkGreen',
  Blue = 'Blue',
  LightOrange = 'LightOrange',
  MidOrange = 'MidOrange',
  DarkOrange = 'DarkOrange',
  LightBlue = 'LightBlue',
  DarkBlue = 'DarkBlue',
  LightRed = 'LightRed',
  DarkRed = 'DarkRed',
  Mint = 'Mint',
  LightGreen = 'LightGreen',
  LightPurple = 'LightPurple',
  DarkPurple = 'DarkPurple',
  Maroon = 'Maroon',
  LavenderBackground = 'LavenderBackground',
  LightBlueBackground = 'LightBlueBackground',
  LavenderBorder = 'LavenderBorder',
  LightBlueBorder = 'LightBlueBorder',
}
