const enum SoilCriterionTypeName {
  HIL = 'HEALTH INVESTIGATION LEVELS',
  HSL = 'HEALTH SCREENING LEVELS',
  EIL = 'ECOLOGICAL INVESTIGATION LEVELS',
  ESL = 'ECOLOGICAL SCREENING LEVELS',
  ML = 'MANAGEMENT LIMITS',
  DC = 'CRC CARE CRITERIA',
  HSL_0_1 = 'HSL FOR DEPTH 0-1m',
  EGV_INDIR = 'ECOLOGICAL INVESTIGATION LEVELS INDIRECT',
}
